# Generated by Django 6.0 on 2025-12-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('discovery_source', models.CharField(max_length=100)),
                ('signal_type', models.CharField(max_length=100)),
                ('signal_strength', models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('discovery_date', models.DateField()),
                ('signal_date', models.CharField(blank=True, default='', max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('timeline', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('source_url', models.URLField(max_length=500, unique=True)),
                ('county', models.CharField(blank=True, default='', max_length=100)),
                ('all_signals', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('won', 'Won'), ('lost', 'Lost'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-discovery_date', '-created_at'],
            },
        ),
    ]
